"""add to model User role

Revision ID: 9ce12f085fed
Revises: 70ad050d0ad2
Create Date: 2025-04-22 18:41:55.653258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ce12f085fed"
down_revision: Union[str, None] = "70ad050d0ad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    stnt = "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole')"
    result = conn.execute(sa.text(stnt)).scalar()
    if not result:
        op.execute("CREATE TYPE userrole AS ENUM ('USER', 'ADMIN')")

    op.add_column(
        "users",
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=True),
    )

    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")

    op.alter_column("users", "role", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")

    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
